### PR TITLE
Fix removing from cart and add Not Found UI

### PR DESCRIPTION
**Pull request by bc-yevhenii-buliuk**
#### What?
This PR fixes the removal of items from the cart when using the "reduce quantity" button.
Also, this PR adds the display of the Not Found user interface on non-existing pages.

#### Screenshots/Videos

**before**

https://github.com/bigcommerce/nextjs-commerce/assets/82589781/aaa1b187-f814-4c64-8619-798fab5a4705

**after**

https://github.com/bigcommerce/nextjs-commerce/assets/82589781/95121022-bd20-4357-9f99-f0259fa51555

**before**

1760_error_not_found

**after**

1760_add_not_found_ui

### CODE REVIEW

**Comment by bc-yevhenii-buliuk** [comment]
@bigcommerce/team-themes Team, could you do a review of this PR? Thanks!

**Review by BC-krasnoshapka — APPROVED** [review]
LGTM!

**Review by bc-alexsaiannyi — APPROVED** [review]
👍

**Review by yurytut1993 — APPROVED** [review]
👌

**Pull request closed without merging**
